/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Projeact11;

import com.example.Projeact11.another.Chess;

public class App {
   
    public static void main(String[] args) {
        Cricket cricketPlayer  = new Cricket(20, "IPL", 11, "Rohit Sharma", "Cricket", false);
        System.out.println("Sport Name " + cricketPlayer.sportsName + "\nMatch Type " + cricketPlayer.matchType +
                "\nCaptain " + cricketPlayer.captainName + "\nOvers " + cricketPlayer.overs + "\nIndoor Game " + cricketPlayer.indoor);
        
        System.out.println();
        
        Chess chessPlayer = new Chess(30, 2000, "Gukesh D", true, "chess", true);
        System.out.println("Sport Name " + chessPlayer.sportsName + "\nPhysical Game " + chessPlayer.physicalOrMind +
                "\nPlayer Name  " + chessPlayer.playerName + "\nTime Factor " + chessPlayer.timeFactor + "\nIndoor Game " + chessPlayer.indoor);
    }
}
